In [1]:
import numpy as np
from scipy import stats
import scipy.stats
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.stats.proportion import proportions_ztest
import matplotlib
import matplotlib.font_manager as fm
from scipy.stats import shapiro


In [4]:
df = pd.DataFrame({"sample": [85.0, 79.0,79.1,79.9,81.6,78.6,85.4,83.4,78.1,79.2]})

t_result = stats.ttest_1samp(df, 78.0)

th = stats.t.ppf(0.975,9)

t,p = t_result.statistic, t_result.pvalue

print(t,p,th)

[3.37924492] [0.00813672] 2.2621571627409915


In [12]:
df1 = pd.DataFrame({"sample": [6,5,5,4,6,7,6,4,5,6,4,5,5,6,4,8,6,5,6,7]})
df2 = pd.DataFrame({"sample": [7,5,7,8,7,8,8,5,7,6,5,5,6,6,5,7,9,7,7,8]})

print(shapiro(df1)) #0.06 -> p값 0.05이상이니까 정규성 만족
print(shapiro(df2)) #0.03 -> p값 0.05미만이니까 정규성 만족

print(stats.levene(df1['sample'], df2['sample'])) # p값 0.05이상이니까 등분산성 만족 -> equal_var 값 = True

t_result = stats.ttest_ind(df1,df2, equal_var = True)
t,p = t_result.statistic, t_result.pvalue
th = stats.t.ppf(0.025,19)
print(t,p, th)

(0.9094840288162231, 0.06230909377336502)
(0.8978105783462524, 0.03752673789858818)
LeveneResult(statistic=0.04810126582278468, pvalue=0.8275746090758196)
[-3.12230485] [0.00342365] -2.0930240544082634


In [18]:
a = pd.DataFrame({"sample": [1.883,1.715,1.799,1.768,1.711,1.832,1.427,1.344]})
b = pd.DataFrame({"sample": [1.435,1.572,1.486,1.511,1.457,1.548,1.404,1.883]})

print(shapiro(a)) #-> 0.05보다 크면 정규성 만족 
print(shapiro(b)) #-> 0.05보다 작으니까 정규성 불만족

print(stats.levene(a['sample'], b['sample'])) #-> 0.05보다 크니까 등분산성 만족 -> equal_var = True

t_result = stats.ttest_ind(a,b,equal_var=True)

t, p = t_result.statistic, t_result.pvalue

th = stats.t.ppf(0.975,7)

print(t,p,th)

(0.8425756096839905, 0.08004552870988846)
(0.7734811902046204, 0.014793740585446358)
LeveneResult(statistic=0.4408416728536036, pvalue=0.5175025061092301)
[1.69953848] [0.11131813] 2.3646242510102993


In [20]:
dfb = pd.DataFrame({"before" : [720,589,780,648,720,589,780,648,780,648]})
dfa = pd.DataFrame({"after" : [710,580,787,712,750,600,782,670,790,680]})

#paired ttest는 정규성 검정 안해도됨

t_result = stats.ttest_rel(dfb,dfa)
t, p = t_result.statistic, t_result.pvalue
print(t,p)
th = stats.t.ppf(0.025,9)
print(th)

[-2.26606522] [0.04968162]
-2.262157162740992


In [25]:
count = 15
n = 100
p = 0.1

stat,p = proportions_ztest(count, n, p)
th = stats.norm.ppf(0.975)
print(stat, p,th)

1.4002800840280094 0.16142946236708322 1.959963984540054


In [28]:
count = 40
n = 100
p = 0.5

stat, p = proportions_ztest(count,n,p)
print(stat,p)
th = stats.norm.ppf(0.025)
print(th)

-2.0412414523193148 0.0412268333371637
-1.9599639845400545


In [30]:
count = np.array([4,1])
n = np.array([1000,1200])
stat, p = proportions_ztest(count, n)
print(stat,p)
th = stats.norm.ppf(0.975)
print(th)

1.553109404737079 0.12039699966295712
1.959963984540054


In [33]:
count = np.array([14,5])
n = np.array([1200,1200])

stat, p = proportions_ztest(count, n)
print(stat,p)
th = stats.norm.ppf(0.975)
print(th)

2.0729633895345208 0.03817568685216671
1.959963984540054


In [41]:
th = stats.chi2.ppf(0.95,3)
print(th)

7.814727903251179


In [44]:
df = pd.DataFrame({"A":[18,1,8,7,10,9,10], "B":[8,2,14,5,5,9,4], "C":[4,1,3,4,9,5,4]
                  ,"D":[4,1,2,3,2,7,3],"E":[3,1,3,1,1,1,1],"F":[3,25,8,10,2,1,7]})

chi2, p, f, ex = stats.chi2_contingency(df)
th = stats.chi2.ppf(0.95,30)
print(th)
print(chi2)
print(p)
print(f)
print(ex)

43.77297182574219
98.27432228716901
3.4707443967367854e-09
30
[[11.00436681  8.20960699  5.24017467  3.84279476  1.92139738  9.78165939]
 [ 8.52838428  6.36244541  4.06113537  2.97816594  1.48908297  7.58078603]
 [10.45414847  7.79912664  4.97816594  3.65065502  1.82532751  9.29257642]
 [ 8.25327511  6.15720524  3.930131    2.88209607  1.44104803  7.33624454]
 [ 7.97816594  5.95196507  3.79912664  2.7860262   1.3930131   7.09170306]
 [ 8.80349345  6.56768559  4.19213974  3.07423581  1.5371179   7.82532751]
 [ 7.97816594  5.95196507  3.79912664  2.7860262   1.3930131   7.09170306]]
