In [19]:
import tensorflow as tf

x1_data = [73,93,89,96,73]
x2_data = [80,88,91,98,66]
x3_data = [75,93,90,100,70]
y_data = [152,185,180,196,142]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name="weight1")
w2 = tf.Variable(tf.random_normal([1]), name="weight2")
w3 = tf.Variable(tf.random_normal([1]), name="weight3")
b = tf.Variable(tf.random_normal([1]), name="bias")
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess= tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis,train], feed_dict={x1:x1_data, x2:x2_data, x3:x3_data, Y:y_data})
    
    if step % 10 == 0 :
        print(step, "Cost:", cost_val, "\nPrediction\n", hy_val)





0 Cost: 4078.0962 
Prediction
 [ 96.68369  115.29489  113.967865 123.52341   88.53334 ]
10 Cost: 1.6678159 
Prediction
 [153.15916 183.18318 180.85469 196.362   140.31683]
20 Cost: 1.6224006 
Prediction
 [153.3253  183.39183 181.0556  196.58131 140.47778]
30 Cost: 1.6143192 
Prediction
 [153.32108 183.39572 181.05476 196.5809  140.48254]
40 Cost: 1.6063254 
Prediction
 [153.31636 183.39896 181.05333 196.57983 140.4868 ]
50 Cost: 1.5983377 
Prediction
 [153.31165 183.4022  181.0519  196.57878 140.49107]
60 Cost: 1.590409 
Prediction
 [153.30693 183.40541 181.05045 196.57771 140.49532]
70 Cost: 1.5825182 
Prediction
 [153.30225 183.40863 181.04901 196.57666 140.49956]
80 Cost: 1.5746819 
Prediction
 [153.29758 183.41183 181.04759 196.5756  140.50378]
90 Cost: 1.5668854 
Prediction
 [153.29291 183.41502 181.04614 196.57457 140.50798]
100 Cost: 1.5591227 
Prediction
 [153.28827 183.41823 181.04474 196.57352 140.51219]
110 Cost: 1.551412 
Prediction
 [153.28363 183.4214  181.04332 196.57246

1210 Cost: 0.91362876 
Prediction
 [152.84323 183.7235  180.90862 196.47307 140.91452]
1220 Cost: 0.9093981 
Prediction
 [152.83981 183.72586 180.90758 196.47229 140.91763]
1230 Cost: 0.9051855 
Prediction
 [152.8364  183.72823 180.90654 196.47151 140.92073]
1240 Cost: 0.9009924 
Prediction
 [152.83298 183.73056 180.90547 196.47072 140.92381]
1250 Cost: 0.89684093 
Prediction
 [152.82957 183.7329  180.90445 196.46997 140.9269 ]
1260 Cost: 0.89270324 
Prediction
 [152.82619 183.73521 180.9034  196.4692  140.92996]
1270 Cost: 0.8885935 
Prediction
 [152.8228  183.73753 180.90237 196.46844 140.93303]
1280 Cost: 0.8844961 
Prediction
 [152.81943 183.73985 180.90132 196.46767 140.93607]
1290 Cost: 0.88041914 
Prediction
 [152.81606 183.74217 180.90031 196.46692 140.93913]
1300 Cost: 0.87637615 
Prediction
 [152.8127  183.74446 180.89928 196.46614 140.94215]
1310 Cost: 0.8723461 
Prediction
 [152.80936 183.74677 180.89825 196.4654  140.94519]
1320 Cost: 0.8683459 
Prediction
 [152.80602 183.

In [21]:
import tensorflow as tf

x_data = [[73,80,75],[93,88,93],[89,91,90],[96,98,100],[73,66,70]]
y_data = [[152.],[185.],[180.],[196.],[142.]]

X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,1])

W = tf.Variable(tf.random_normal([3,1], name="weight"))
b = tf.Variable(tf.random_normal([1]), name="bias")
          
hypothesis = tf.matmul(X,W) + b 

cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess= tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis,train], feed_dict={X:x_data, Y:y_data})
    
    if step % 10 == 0 :
        print(step, "Cost:", cost_val, "\nPrediction\n", hy_val)






0 Cost: 48985.836 
Prediction
 [[-52.165997]
 [-46.35809 ]
 [-54.205658]
 [-58.258926]
 [-31.836014]]
10 Cost: 25.229122 
Prediction
 [[143.59349]
 [188.89365]
 [177.6109 ]
 [194.18121]
 [147.59464]]
20 Cost: 24.648123 
Prediction
 [[144.20506]
 [189.59224]
 [178.31822]
 [194.94916]
 [148.12032]]
30 Cost: 24.51611 
Prediction
 [[144.2261 ]
 [189.58118]
 [178.32626]
 [194.95563]
 [148.10474]]
40 Cost: 24.384869 
Prediction
 [[144.24533]
 [189.56805]
 [178.33218]
 [194.9598 ]
 [148.08759]]
50 Cost: 24.254215 
Prediction
 [[144.26451]
 [189.55492]
 [178.33807]
 [194.96391]
 [148.07047]]
60 Cost: 24.124353 
Prediction
 [[144.28362]
 [189.54182]
 [178.34395]
 [194.96803]
 [148.05339]]
70 Cost: 23.995148 
Prediction
 [[144.30267]
 [189.52875]
 [178.3498 ]
 [194.97214]
 [148.03636]]
80 Cost: 23.866657 
Prediction
 [[144.3217 ]
 [189.51575]
 [178.35565]
 [194.97626]
 [148.0194 ]]
90 Cost: 23.73881 
Prediction
 [[144.34065]
 [189.50273]
 [178.36147]
 [194.98032]
 [148.00244]]
100 Cost: 23.61172

940 Cost: 15.057385 
Prediction
 [[145.77878]
 [188.51796]
 [178.80348]
 [195.28937]
 [146.71918]]
950 Cost: 14.97717 
Prediction
 [[145.79381]
 [188.50766]
 [178.80809]
 [195.29256]
 [146.70576]]
960 Cost: 14.897405 
Prediction
 [[145.8088 ]
 [188.4974 ]
 [178.81271]
 [195.29579]
 [146.69241]]
970 Cost: 14.818031 
Prediction
 [[145.82376]
 [188.48717]
 [178.81732]
 [195.299  ]
 [146.67908]]
980 Cost: 14.739139 
Prediction
 [[145.83867]
 [188.47696]
 [178.8219 ]
 [195.30217]
 [146.66579]]
990 Cost: 14.660677 
Prediction
 [[145.85353]
 [188.46677]
 [178.82648]
 [195.30536]
 [146.65254]]
1000 Cost: 14.582593 
Prediction
 [[145.86838]
 [188.45662]
 [178.83104]
 [195.30853]
 [146.63933]]
1010 Cost: 14.504933 
Prediction
 [[145.88316]
 [188.44649]
 [178.83559]
 [195.31169]
 [146.62613]]
1020 Cost: 14.427768 
Prediction
 [[145.8979 ]
 [188.43639]
 [178.8401 ]
 [195.31483]
 [146.61299]]
1030 Cost: 14.35097 
Prediction
 [[145.91261]
 [188.42632]
 [178.84464]
 [195.318  ]
 [146.59988]]
1040 Cos

1910 Cost: 8.9900875 
Prediction
 [[147.06325]
 [187.63861]
 [179.1986 ]
 [195.56314]
 [145.57541]]
1920 Cost: 8.942665 
Prediction
 [[147.07483]
 [187.6307 ]
 [179.20215]
 [195.56558]
 [145.56512]]
1930 Cost: 8.895502 
Prediction
 [[147.08636]
 [187.6228 ]
 [179.2057 ]
 [195.56804]
 [145.55487]]
1940 Cost: 8.848608 
Prediction
 [[147.09787]
 [187.61493]
 [179.20924]
 [195.57048]
 [145.54465]]
1950 Cost: 8.801962 
Prediction
 [[147.10934]
 [187.60709]
 [179.21277]
 [195.5729 ]
 [145.53444]]
1960 Cost: 8.755524 
Prediction
 [[147.12079]
 [187.59924]
 [179.2163 ]
 [195.57533]
 [145.52425]]
1970 Cost: 8.709388 
Prediction
 [[147.1322 ]
 [187.59143]
 [179.21982]
 [195.57776]
 [145.51411]]
1980 Cost: 8.663448 
Prediction
 [[147.14359]
 [187.58362]
 [179.22331]
 [195.58017]
 [145.50398]]
1990 Cost: 8.617823 
Prediction
 [[147.15494]
 [187.57587]
 [179.2268 ]
 [195.58257]
 [145.4939 ]]
2000 Cost: 8.572404 
Prediction
 [[147.16624]
 [187.5681 ]
 [179.23027]
 [195.58495]
 [145.48381]]


In [26]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:,0:-1]
y_data = xy[:,[-1]]

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3,1]), name="weight")
b = tf.Variable(tf.random_normal([1]), name="bias")

hypothesis = tf.matmul(X,W) + b

cost = tf.reduce_mean(tf.square(hypothesis-Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X:x_data, Y:y_data})
    if step % 10 == 0:
        print(step,"Cost :", cost_val, "\nPrediction\n", hy_val)

print("your score will be", sess.run(hypothesis, feed_dict={X:[[100,70,101]]}))
print("other scores will be", sess.run(hypothesis, feed_dict={X:[[60,70,110],[90,100,80]]}))





0 Cost : 109.90017 
Prediction
 [[160.33209 ]
 [197.42685 ]
 [192.17668 ]
 [207.78998 ]
 [153.07706 ]
 [111.26589 ]
 [152.11165 ]
 [107.794586]
 [183.85904 ]
 [167.51476 ]
 [149.50858 ]
 [148.9832  ]
 [200.12654 ]
 [168.86774 ]
 [153.36458 ]
 [198.48999 ]
 [164.12259 ]
 [180.41997 ]
 [190.30519 ]
 [169.5349  ]
 [179.51442 ]
 [183.49527 ]
 [171.18439 ]
 [165.31511 ]
 [204.53615 ]]
10 Cost : 36.72028 
Prediction
 [[152.35031]
 [187.83281]
 [182.72307]
 [197.504  ]
 [145.7518 ]
 [105.88025]
 [144.42693]
 [102.11818]
 [174.90446]
 [159.24213]
 [142.09453]
 [141.67624]
 [190.34962]
 [160.72624]
 [145.64552]
 [188.76366]
 [156.3568 ]
 [171.20389]
 [180.98282]
 [161.19547]
 [170.49931]
 [174.50433]
 [162.58646]
 [157.24434]
 [194.5885 ]]
20 Cost : 36.528797 
Prediction
 [[152.29106]
 [187.76088]
 [182.65175]
 [197.43607]
 [145.68877]
 [105.84867]
 [144.3907 ]
 [102.11181]
 [174.84894]
 [159.21208]
 [142.04945]
 [141.6352 ]
 [190.26598]
 [160.64278]
 [145.6101 ]
 [188.69998]
 [156.26529]
 [171

470 Cost : 29.24059 
Prediction
 [[152.13965]
 [187.50961]
 [182.40698]
 [197.57024]
 [145.14923]
 [106.06142]
 [145.10693]
 [103.50569]
 [175.08788]
 [160.31334]
 [142.30711]
 [142.01242]
 [189.60033]
 [159.51021]
 [146.36366]
 [188.83379]
 [154.67795]
 [172.29578]
 [180.21394]
 [160.5897 ]
 [171.14052]
 [174.60686]
 [163.08658]
 [156.05214]
 [194.07045]]
480 Cost : 29.101852 
Prediction
 [[152.13698 ]
 [187.50414 ]
 [182.4021  ]
 [197.57307 ]
 [145.13776 ]
 [106.065285]
 [145.12183 ]
 [103.53467 ]
 [175.09222 ]
 [160.33519 ]
 [142.3124  ]
 [142.01978 ]
 [189.58685 ]
 [159.48714 ]
 [146.3792  ]
 [188.83623 ]
 [154.64537 ]
 [172.31935 ]
 [180.20015 ]
 [160.5791  ]
 [171.15477 ]
 [174.60985 ]
 [163.09804 ]
 [156.02995 ]
 [194.06128 ]]
490 Cost : 28.964083 
Prediction
 [[152.13437]
 [187.49867]
 [182.39725]
 [197.57591]
 [145.12631]
 [106.06913]
 [145.13672]
 [103.56356]
 [175.09651]
 [160.35695]
 [142.31769]
 [142.0271 ]
 [189.57346]
 [159.4642 ]
 [146.39468]
 [188.83865]
 [154.61293]
 

970 Cost : 23.29533 
Prediction
 [[152.03777 ]
 [187.24297 ]
 [182.18794 ]
 [197.70462 ]
 [144.60228 ]
 [106.216965]
 [145.80292 ]
 [104.858246]
 [175.26105 ]
 [161.28543 ]
 [142.5515  ]
 [142.33286 ]
 [188.98846 ]
 [158.45709 ]
 [147.0826  ]
 [188.93237 ]
 [153.17683 ]
 [173.40034 ]
 [179.59344 ]
 [160.11795 ]
 [171.80319 ]
 [174.73051 ]
 [163.62416 ]
 [155.05634 ]
 [193.64035 ]]
980 Cost : 23.19477 
Prediction
 [[152.0363 ]
 [187.23776]
 [182.18405]
 [197.70715]
 [144.59189]
 [106.21935]
 [145.81586]
 [104.88339]
 [175.26367]
 [161.30255]
 [142.55598]
 [142.33836]
 [188.9774 ]
 [158.43797]
 [147.09584]
 [188.93388]
 [153.14932]
 [173.42097]
 [179.58237]
 [160.10965]
 [171.81546]
 [174.7325 ]
 [163.63422]
 [155.03862]
 [193.63231]]
990 Cost : 23.094854 
Prediction
 [[152.03487 ]
 [187.2326  ]
 [182.18018 ]
 [197.70967 ]
 [144.5815  ]
 [106.22172 ]
 [145.82877 ]
 [104.908455]
 [175.26628 ]
 [161.3196  ]
 [142.56046 ]
 [142.34384 ]
 [188.96642 ]
 [158.4189  ]
 [147.10902 ]
 [188.93538 ]

1470 Cost : 18.968176 
Prediction
 [[151.98782 ]
 [186.99146 ]
 [182.01337 ]
 [197.82451 ]
 [144.10703 ]
 [106.30792 ]
 [146.40765 ]
 [106.032196]
 [175.36046 ]
 [162.04584 ]
 [142.75853 ]
 [142.57143 ]
 [188.48628 ]
 [157.58212 ]
 [147.69583 ]
 [188.99065 ]
 [151.90718 ]
 [174.36662 ]
 [179.09482 ]
 [159.7489  ]
 [172.37451 ]
 [174.80992 ]
 [164.09659 ]
 [154.26105 ]
 [193.2631  ]]
1480 Cost : 18.894651 
Prediction
 [[151.98724 ]
 [186.98657 ]
 [182.01027 ]
 [197.82675 ]
 [144.09763 ]
 [106.309204]
 [146.41891 ]
 [106.05403 ]
 [175.36182 ]
 [162.0592  ]
 [142.76233 ]
 [142.5755  ]
 [188.4772  ]
 [157.56621 ]
 [147.70714 ]
 [188.99149 ]
 [151.88387 ]
 [174.38467 ]
 [179.0859  ]
 [159.7424  ]
 [172.38509 ]
 [174.81113 ]
 [164.10541 ]
 [154.24689 ]
 [193.25604 ]]
1490 Cost : 18.821583 
Prediction
 [[151.98668 ]
 [186.98172 ]
 [182.00717 ]
 [197.829   ]
 [144.08823 ]
 [106.310455]
 [146.43013 ]
 [106.0758  ]
 [175.36317 ]
 [162.07251 ]
 [142.76611 ]
 [142.57954 ]
 [188.46814 ]
 [157.55035

1940 Cost : 15.956921 
Prediction
 [[151.9756  ]
 [186.77014 ]
 [181.88179 ]
 [197.92525 ]
 [143.68542 ]
 [106.349594]
 [146.9042  ]
 [106.99515 ]
 [175.40396 ]
 [162.60728 ]
 [142.92455 ]
 [142.73756 ]
 [188.09592 ]
 [156.8936  ]
 [148.19083 ]
 [189.01807 ]
 [150.89053 ]
 [175.16489 ]
 [178.71564 ]
 [159.47636 ]
 [172.84026 ]
 [174.85414 ]
 [164.48846 ]
 [153.66025 ]
 [192.95068 ]]
1950 Cost : 15.901745 
Prediction
 [[151.97562]
 [186.76556]
 [181.87927]
 [197.92726]
 [143.67688]
 [106.3501 ]
 [146.91406]
 [107.01429]
 [175.40445]
 [162.61784]
 [142.9278 ]
 [142.74055]
 [188.08835]
 [156.88017]
 [148.20056]
 [189.01842]
 [150.87053]
 [175.1808 ]
 [178.70836]
 [159.47122]
 [172.84946]
 [174.85481]
 [164.49628]
 [153.6488 ]
 [192.94443]]
1960 Cost : 15.8468895 
Prediction
 [[151.97566]
 [186.76105]
 [181.87679]
 [197.9293 ]
 [143.66837]
 [106.35061]
 [146.92393]
 [107.0334 ]
 [175.40494]
 [162.62837]
 [142.93106]
 [142.74358]
 [188.08083]
 [156.86682]
 [148.21031]
 [189.01875]
 [150.850