In [10]:
colors = ['red', 'green', 'blue']
result = list(enumerate(colors))
print(result)

[(0, 'red'), (1, 'green'), (2, 'blue')]


In [8]:
ls = [num ** 2 for num in range(1,6)]
print(ls)

[1, 4, 9, 16, 25]


In [9]:
a = [1,2,3]
b = [3,4,5]
c = [x * y for x in a for y in b]
print(c)

[3, 4, 5, 6, 8, 10, 9, 12, 15]


In [13]:
import numpy as np

a = np.array([1,2,3]) # 1차원 array [1,2,3] 생성
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5
print(a)
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])
print(b[0][0])

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4
1


In [14]:
import numpy as np
a = np.zeros((2,2)) # 모든 값이 0인 2x2 array 생성
print(a)
b = np.ones((1,2)) # 모든 값이 1인 1x2 array 생성
print(b)
c = np.full((2,2), 7) # 모든 값이 7인 2x2 array 생성
print(c)
d = np.eye(2) # 2x2 단위행렬(Identity matrix) 생성
print(d)
e = np.random.random((2,2)) # 0~1 랜덤 값을 가지는 2x2 array 생성
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.09470312 0.62905311]
 [0.97248978 0.87184106]]


In [19]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = a[:, 1:3]
print(b)
print(a[0, 1])
b[0, 0] = 77
print(a[0, 1])
print(b)
# Slicing을 한다고 해서 값을 복사해가는 것이 아니므로
# 값의 변화가 동시에 일어남

[[ 2  3]
 [ 6  7]
 [10 11]]
2
77
[[77  3]
 [ 6  7]
 [10 11]]


In [20]:
import numpy as np
# 2차원 배열(3x4) 생성
# [[ 1 2 3 4]
# [ 5 6 7 8]
# [ 9 10 11 12]]
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
# 두 번째 행의 값들을 모두 가져오는 두 가지 방법
row_r1 = a[1, :]
# 1차원 행렬 (4,)
row_r2 = a[1:2, :] # 2차원 행렬 (1x4) – 기존 차원 유지
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
# 두 번째 열의
col_r1 = a[:,1]
col_r2 = a[:,1:2]
print(col_r1,col_r1.shape)

print(col_r2,col_r2.shape)


[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [21]:
import numpy as np
# 2차원 배열(3x2) 생성
# [[ 1 2]
# [ 3 4]
# [ 5 6]]
a = np.array([[1, 2], [3, 4], [5, 6]])
# [1 4 5] 1차원 행렬(3,)을 얻는 두 가지 방법
print(a[[0, 1, 2], [0, 1, 0]])
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))
# [2 2] 1차원 행렬(2,)을 얻는 두 가지 방법
print(a[[0, 0], [1, 1]])
print(np.array([a[0, 1], a[0, 1]]))

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [22]:
import numpy as np
# 2차원 배열(4x3) 생성

a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)
b = np.array([0, 2, 0, 1])
print(a[np.arange(4), b]) # [1 6 7 11]
a[np.arange(4), b] += 10
print(a) # array([[11, 2, 3],



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [24]:
import numpy as np
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)
print(x + y)
print(np.add(x, y))
print(x - y)
print(np.subtract(x, y))
print(x * y)
print(np.multiply(x, y))
print(x / y)
print(np.divide(x, y))
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [25]:
import numpy as np
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
# v · w = 219
print(v.dot(w))
print(np.dot(v, w))
# 매트릭스 / 벡터 곱; [29 67]
print(x.dot(v))
print(np.dot(x, v))
# 매트릭스 / 매트릭스 곱;
# [[19 22]
#[43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [26]:
import numpy as np
x = np.array([[1, 2], [3, 4]])
print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

10
[4 6]
[3 7]


In [29]:
a = np.ones((2,3,4))
print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))
print(np.sum(a, axis=2))

24.0
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]]
[[4. 4. 4.]
 [4. 4. 4.]]


In [30]:
import numpy as np
x = np.array([[1, 2], [3, 4]])
print(x)
print(x.T)
# 전치행렬 (Transposed mat.)
v = np.array([1,2,3])
print(v)
# prints “[1 2 3]”
print(v.T)
# pr

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


In [35]:
import numpy as np
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1,0,1])
y = np.empty_like(x) # x와 같은 shape의 빈 매트릭스 만들기
# x의 각 행에 v와 elementwise 합을 하여 y의 해당 행에 할당
print(x)


for i in range(4):
    y[i] = x[i] + v
# [[ 2 2 4]
# [[ 5 5 7]
# [[ 8 8 10]
# [ 11 11 13]]
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [36]:
import numpy as np
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1,0,1])
vv = np.tile(v, (4, 1)) # v 내용을 4x1의 각 행에 반복함
print(vv)
# [[ 2 2 4]
# [[ 5 5 7]
# [[ 8 8 10]
# [ 11 11 13]]
y = x + vv
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [37]:
import numpy as np
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1,0,1])
# 브로드캐스팅을 사용하여 x의 각 행에 v값을 더함
y = x + v
# [[ 2 2 4]
# [[ 5 5 7]
# [[ 8 8 10]
# [ 11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [42]:
a = np.array([1,2,3])
a1 = a.reshape([3,1])
print(a1)


[[1]
 [2]
 [3]]


In [56]:
import numpy as np
a = np.array([[1,1], [2,1]])
b = np.linalg.inv(a) #역행렬
c = np.array([15,25])
c = c.reshape([2,1])
d = b.dot(c)
print(d)



[[10.]
 [ 5.]]


In [19]:
import numpy as np

x1 = np.array([0,0])
x2 = np.array([0,1])
x3 = np.array([1,0])
x4 = np.array([1,1])
x_list = [x1, x2, x3, x4]
values = []
true = [0,0,0,1]

while True:
    w = np.random.random((2,2))
    b = np.random.random((2,))
    for i in x_list:
        result = w.dot(i) + b
        value = np.argmax(result)
        values.append(value)
    if values == true :
        break
    values = []
    


print("w :",w)
print("b :",b)
print(values)

num = 0 
for i in x_list:
    result = w.dot(i) + b
    value = np.argmax(result)
    print("f(W · x%d + b) = %d" %(num,value))
    num +=1




w : [[0.41795458 0.687954  ]
 [0.7383943  0.89623833]]
b : [0.56666943 0.08427415]
[0, 0, 0, 1]
f(W · x0 + b) = 0
f(W · x1 + b) = 0
f(W · x2 + b) = 0
f(W · x3 + b) = 1


In [1]:
word = 'python' 
num = len(word)
temp = 0
while temp < num:
    print(word[temp])
    temp +=1


p
y
t
h
o
n
